export const SAVE_TEACHER = 'SAVE_TEACHER';
export const GET_TEACHERS = 'GET_TEACHERS';
export const REMOVE_TEACHER = 'REMOVE_TEACHER';
export const CHANGE_VALUE_TEACHER = 'CHANGE_VALUE_TEACHER';
export const CLEAR_TEACHER = 'CLEAR_TEACHER';