export const SHOW_SUCCESS = 'SHOW_SUCCESS';
export const SHOW_ERROR = 'SHOW_ERROR';
export const SHOW_DELETE_SUCCESS = 'SHOW_DELETE_SUCCESS';
export const SHOW_FOREIGN_KEY_ERROR = 'SHOW_FOREIGN_KEY_ERROR';