export const SAVE_SECTOR = 'SAVE_SECTOR';
export const GET_SECTORS = 'GET_SECTORS';
export const REMOVE_SECTOR = 'REMOVE_SECTOR';
export const CHANGE_VALUE_SECTOR = 'CHANGE_VALUE_SECTOR';
export const CLEAR_SECTOR = 'CLEAR_SECTOR';