export const SAVE_MODALITY = 'SAVE_MODALITY';
export const GET_MODALITIES = 'GET_MODALITIES';
export const REMOVE_MODALITY  = 'REMOVE_MODALITY';
export const CHANGE_VALUE_MODALITY = 'CHANGE_VALUE_MODALITY';
export const CLEAR_MODALITY = 'CLEAR_MODALITY';