export const SAVE_MODALITY = 'SAVE_MODALITY';
export const GET_MODALITIES = 'GET_MODALITIES';
export const REMOVE_MODALITY  = 'REMOVE_MODALITY';
export const CHANGE_VALUE = 'CHANGE_VALUE';
export const CLEAR = 'CLEAR';