export const SAVE_EMPLOYEE = 'SAVE_EMPLOYEE';
export const GET_EMPLOYEES = 'GET_EMPLOYEES';
export const REMOVE_EMPLOYEE = 'REMOVE_EMPLOYEE';
export const CHANGE_VALUE_EMPLOYEE = 'CHANGE_VALUE_EMPLOYEE';
export const CLEAR_EMPLOYEE = 'CLEAR_EMPLOYEE';